### ISSUE TITLE
"getfeedback" should be "get feedback"

### ISSUE THREAD

**Issue by onemriganka** [uramakilab/gsoc#1]
while I was reading the readme.md for contributors guide, i found that "getfeedback " should be "get feedback" that's, why I made this issue. thanks

![Screenshot 2024-02-23 184939](https://github.com/ruxailab/gsoc/assets/119776446/4eb454ad-d2fb-487d-8a7f-4179c672e6cc)

**Comment by onemriganka** [comment]
#1 / attempted

**Comment by kartik912** [comment]
i have made the changes , and fixed your issue. Please consider my PR

**Comment by amanreddy77** [comment]
I have fixed all other spelling mistakes and grammatical errors in the README.md file
